/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InvoiceId = IDL.Nat;
export const PaymentMethod = IDL.Variant({
  'creditCard' : IDL.Null,
  'other' : IDL.Text,
  'cash' : IDL.Null,
  'check' : IDL.Null,
  'bankTransfer' : IDL.Null,
});
export const PaymentId = IDL.Nat;
export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const CustomerId = IDL.Nat;
export const SalesOrderId = IDL.Nat;
export const Time = IDL.Int;
export const SupplierId = IDL.Nat;
export const PurchaseOrderLineItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'unitCost' : IDL.Nat,
});
export const PurchaseOrderId = IDL.Nat;
export const SalesOrderLineItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const CustomerReceivable = IDL.Record({
  'customerName' : IDL.Text,
  'totalOutstanding' : IDL.Nat,
  'customerId' : CustomerId,
});
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : Address,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const InvoiceStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'partial' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : InvoiceId,
  'status' : InvoiceStatus,
  'createdAt' : Time,
  'dueDate' : Time,
  'amountPaid' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'salesOrderId' : SalesOrderId,
  'customerId' : CustomerId,
});
export const Payment = IDL.Record({
  'id' : PaymentId,
  'method' : PaymentMethod,
  'invoiceId' : InvoiceId,
  'notes' : IDL.Text,
  'paymentDate' : Time,
  'amount' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'sku' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'quantityOnHand' : IDL.Nat,
  'category' : IDL.Text,
  'reorderLevel' : IDL.Nat,
  'unitCost' : IDL.Nat,
});
export const PurchaseOrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'sent' : IDL.Null,
  'draft' : IDL.Null,
  'received' : IDL.Null,
});
export const PurchaseOrder = IDL.Record({
  'id' : PurchaseOrderId,
  'status' : PurchaseOrderStatus,
  'lineItems' : IDL.Vec(PurchaseOrderLineItem),
  'createdAt' : Time,
  'receivedAt' : IDL.Opt(Time),
  'supplierId' : SupplierId,
});
export const SalesOrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'draft' : IDL.Null,
});
export const SalesOrder = IDL.Record({
  'id' : SalesOrderId,
  'status' : SalesOrderStatus,
  'lineItems' : IDL.Vec(SalesOrderLineItem),
  'createdAt' : Time,
  'confirmedAt' : IDL.Opt(Time),
  'shippedAt' : IDL.Opt(Time),
  'customerId' : CustomerId,
});
export const Supplier = IDL.Record({
  'id' : SupplierId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : Address,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'lowStockProducts' : IDL.Vec(Product),
  'outstandingReceivables' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'recentSalesOrdersCount' : IDL.Nat,
});
export const SalesSummary = IDL.Record({
  'totalSales' : IDL.Nat,
  'orderCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPayment' : IDL.Func(
      [InvoiceId, IDL.Nat, PaymentMethod, IDL.Text],
      [PaymentId],
      [],
    ),
  'adjustStock' : IDL.Func([ProductId, IDL.Int], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Address, IDL.Text],
      [CustomerId],
      [],
    ),
  'createInvoice' : IDL.Func([SalesOrderId, Time], [InvoiceId], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [ProductId],
      [],
    ),
  'createPurchaseOrder' : IDL.Func(
      [SupplierId, IDL.Vec(PurchaseOrderLineItem)],
      [PurchaseOrderId],
      [],
    ),
  'createSalesOrder' : IDL.Func(
      [CustomerId, IDL.Vec(SalesOrderLineItem)],
      [SalesOrderId],
      [],
    ),
  'createSupplier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Address, IDL.Text],
      [SupplierId],
      [],
    ),
  'deleteCustomer' : IDL.Func([CustomerId], [], []),
  'deleteInvoice' : IDL.Func([InvoiceId], [], []),
  'deletePayment' : IDL.Func([PaymentId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'deletePurchaseOrder' : IDL.Func([PurchaseOrderId], [], []),
  'deleteSalesOrder' : IDL.Func([SalesOrderId], [], []),
  'deleteSupplier' : IDL.Func([SupplierId], [], []),
  'getAccountsReceivable' : IDL.Func(
      [],
      [IDL.Vec(CustomerReceivable)],
      ['query'],
    ),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
  'getAllSalesOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
  'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getInventoryValuation' : IDL.Func([], [IDL.Nat], ['query']),
  'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
  'getPayment' : IDL.Func([PaymentId], [IDL.Opt(Payment)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getPurchaseOrder' : IDL.Func(
      [PurchaseOrderId],
      [IDL.Opt(PurchaseOrder)],
      ['query'],
    ),
  'getSalesOrder' : IDL.Func([SalesOrderId], [IDL.Opt(SalesOrder)], ['query']),
  'getSalesSummary' : IDL.Func([Time, Time], [SalesSummary], ['query']),
  'getSupplier' : IDL.Func([SupplierId], [IDL.Opt(Supplier)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomer' : IDL.Func(
      [CustomerId, IDL.Text, IDL.Text, IDL.Text, Address, IDL.Text],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updatePurchaseOrderStatus' : IDL.Func(
      [PurchaseOrderId, PurchaseOrderStatus],
      [],
      [],
    ),
  'updateSalesOrderStatus' : IDL.Func([SalesOrderId, SalesOrderStatus], [], []),
  'updateSupplier' : IDL.Func(
      [SupplierId, IDL.Text, IDL.Text, IDL.Text, Address, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InvoiceId = IDL.Nat;
  const PaymentMethod = IDL.Variant({
    'creditCard' : IDL.Null,
    'other' : IDL.Text,
    'cash' : IDL.Null,
    'check' : IDL.Null,
    'bankTransfer' : IDL.Null,
  });
  const PaymentId = IDL.Nat;
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const CustomerId = IDL.Nat;
  const SalesOrderId = IDL.Nat;
  const Time = IDL.Int;
  const SupplierId = IDL.Nat;
  const PurchaseOrderLineItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'unitCost' : IDL.Nat,
  });
  const PurchaseOrderId = IDL.Nat;
  const SalesOrderLineItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const CustomerReceivable = IDL.Record({
    'customerName' : IDL.Text,
    'totalOutstanding' : IDL.Nat,
    'customerId' : CustomerId,
  });
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : Address,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InvoiceStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'partial' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : InvoiceId,
    'status' : InvoiceStatus,
    'createdAt' : Time,
    'dueDate' : Time,
    'amountPaid' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'salesOrderId' : SalesOrderId,
    'customerId' : CustomerId,
  });
  const Payment = IDL.Record({
    'id' : PaymentId,
    'method' : PaymentMethod,
    'invoiceId' : InvoiceId,
    'notes' : IDL.Text,
    'paymentDate' : Time,
    'amount' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'sku' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'quantityOnHand' : IDL.Nat,
    'category' : IDL.Text,
    'reorderLevel' : IDL.Nat,
    'unitCost' : IDL.Nat,
  });
  const PurchaseOrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'sent' : IDL.Null,
    'draft' : IDL.Null,
    'received' : IDL.Null,
  });
  const PurchaseOrder = IDL.Record({
    'id' : PurchaseOrderId,
    'status' : PurchaseOrderStatus,
    'lineItems' : IDL.Vec(PurchaseOrderLineItem),
    'createdAt' : Time,
    'receivedAt' : IDL.Opt(Time),
    'supplierId' : SupplierId,
  });
  const SalesOrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'draft' : IDL.Null,
  });
  const SalesOrder = IDL.Record({
    'id' : SalesOrderId,
    'status' : SalesOrderStatus,
    'lineItems' : IDL.Vec(SalesOrderLineItem),
    'createdAt' : Time,
    'confirmedAt' : IDL.Opt(Time),
    'shippedAt' : IDL.Opt(Time),
    'customerId' : CustomerId,
  });
  const Supplier = IDL.Record({
    'id' : SupplierId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : Address,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'lowStockProducts' : IDL.Vec(Product),
    'outstandingReceivables' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'recentSalesOrdersCount' : IDL.Nat,
  });
  const SalesSummary = IDL.Record({
    'totalSales' : IDL.Nat,
    'orderCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPayment' : IDL.Func(
        [InvoiceId, IDL.Nat, PaymentMethod, IDL.Text],
        [PaymentId],
        [],
      ),
    'adjustStock' : IDL.Func([ProductId, IDL.Int], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Address, IDL.Text],
        [CustomerId],
        [],
      ),
    'createInvoice' : IDL.Func([SalesOrderId, Time], [InvoiceId], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [ProductId],
        [],
      ),
    'createPurchaseOrder' : IDL.Func(
        [SupplierId, IDL.Vec(PurchaseOrderLineItem)],
        [PurchaseOrderId],
        [],
      ),
    'createSalesOrder' : IDL.Func(
        [CustomerId, IDL.Vec(SalesOrderLineItem)],
        [SalesOrderId],
        [],
      ),
    'createSupplier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Address, IDL.Text],
        [SupplierId],
        [],
      ),
    'deleteCustomer' : IDL.Func([CustomerId], [], []),
    'deleteInvoice' : IDL.Func([InvoiceId], [], []),
    'deletePayment' : IDL.Func([PaymentId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'deletePurchaseOrder' : IDL.Func([PurchaseOrderId], [], []),
    'deleteSalesOrder' : IDL.Func([SalesOrderId], [], []),
    'deleteSupplier' : IDL.Func([SupplierId], [], []),
    'getAccountsReceivable' : IDL.Func(
        [],
        [IDL.Vec(CustomerReceivable)],
        ['query'],
      ),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
    'getAllSalesOrders' : IDL.Func([], [IDL.Vec(SalesOrder)], ['query']),
    'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getInventoryValuation' : IDL.Func([], [IDL.Nat], ['query']),
    'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
    'getPayment' : IDL.Func([PaymentId], [IDL.Opt(Payment)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getPurchaseOrder' : IDL.Func(
        [PurchaseOrderId],
        [IDL.Opt(PurchaseOrder)],
        ['query'],
      ),
    'getSalesOrder' : IDL.Func(
        [SalesOrderId],
        [IDL.Opt(SalesOrder)],
        ['query'],
      ),
    'getSalesSummary' : IDL.Func([Time, Time], [SalesSummary], ['query']),
    'getSupplier' : IDL.Func([SupplierId], [IDL.Opt(Supplier)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomer' : IDL.Func(
        [CustomerId, IDL.Text, IDL.Text, IDL.Text, Address, IDL.Text],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updatePurchaseOrderStatus' : IDL.Func(
        [PurchaseOrderId, PurchaseOrderStatus],
        [],
        [],
      ),
    'updateSalesOrderStatus' : IDL.Func(
        [SalesOrderId, SalesOrderStatus],
        [],
        [],
      ),
    'updateSupplier' : IDL.Func(
        [SupplierId, IDL.Text, IDL.Text, IDL.Text, Address, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };