/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
}
export interface Customer {
  'id' : CustomerId,
  'name' : string,
  'email' : string,
  'address' : Address,
  'notes' : string,
  'phone' : string,
}
export type CustomerId = bigint;
export interface CustomerReceivable {
  'customerName' : string,
  'totalOutstanding' : bigint,
  'customerId' : CustomerId,
}
export interface DashboardStats {
  'lowStockProducts' : Array<Product>,
  'outstandingReceivables' : bigint,
  'totalRevenue' : bigint,
  'recentSalesOrdersCount' : bigint,
}
export interface Invoice {
  'id' : InvoiceId,
  'status' : InvoiceStatus,
  'createdAt' : Time,
  'dueDate' : Time,
  'amountPaid' : bigint,
  'totalAmount' : bigint,
  'salesOrderId' : SalesOrderId,
  'customerId' : CustomerId,
}
export type InvoiceId = bigint;
export type InvoiceStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'partial' : null };
export interface Payment {
  'id' : PaymentId,
  'method' : PaymentMethod,
  'invoiceId' : InvoiceId,
  'notes' : string,
  'paymentDate' : Time,
  'amount' : bigint,
}
export type PaymentId = bigint;
export type PaymentMethod = { 'creditCard' : null } |
  { 'other' : string } |
  { 'cash' : null } |
  { 'check' : null } |
  { 'bankTransfer' : null };
export interface Product {
  'id' : ProductId,
  'sku' : string,
  'name' : string,
  'description' : string,
  'quantityOnHand' : bigint,
  'category' : string,
  'reorderLevel' : bigint,
  'unitCost' : bigint,
}
export type ProductId = bigint;
export interface PurchaseOrder {
  'id' : PurchaseOrderId,
  'status' : PurchaseOrderStatus,
  'lineItems' : Array<PurchaseOrderLineItem>,
  'createdAt' : Time,
  'receivedAt' : [] | [Time],
  'supplierId' : SupplierId,
}
export type PurchaseOrderId = bigint;
export interface PurchaseOrderLineItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'unitCost' : bigint,
}
export type PurchaseOrderStatus = { 'cancelled' : null } |
  { 'sent' : null } |
  { 'draft' : null } |
  { 'received' : null };
export interface SalesOrder {
  'id' : SalesOrderId,
  'status' : SalesOrderStatus,
  'lineItems' : Array<SalesOrderLineItem>,
  'createdAt' : Time,
  'confirmedAt' : [] | [Time],
  'shippedAt' : [] | [Time],
  'customerId' : CustomerId,
}
export type SalesOrderId = bigint;
export interface SalesOrderLineItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type SalesOrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'draft' : null };
export interface SalesSummary { 'totalSales' : bigint, 'orderCount' : bigint }
export interface Supplier {
  'id' : SupplierId,
  'name' : string,
  'email' : string,
  'address' : Address,
  'notes' : string,
  'phone' : string,
}
export type SupplierId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPayment' : ActorMethod<
    [InvoiceId, bigint, PaymentMethod, string],
    PaymentId
  >,
  'adjustStock' : ActorMethod<[ProductId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomer' : ActorMethod<
    [string, string, string, Address, string],
    CustomerId
  >,
  'createInvoice' : ActorMethod<[SalesOrderId, Time], InvoiceId>,
  'createProduct' : ActorMethod<
    [string, string, string, string, bigint, bigint, bigint],
    ProductId
  >,
  'createPurchaseOrder' : ActorMethod<
    [SupplierId, Array<PurchaseOrderLineItem>],
    PurchaseOrderId
  >,
  'createSalesOrder' : ActorMethod<
    [CustomerId, Array<SalesOrderLineItem>],
    SalesOrderId
  >,
  'createSupplier' : ActorMethod<
    [string, string, string, Address, string],
    SupplierId
  >,
  'deleteCustomer' : ActorMethod<[CustomerId], undefined>,
  'deleteInvoice' : ActorMethod<[InvoiceId], undefined>,
  'deletePayment' : ActorMethod<[PaymentId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'deletePurchaseOrder' : ActorMethod<[PurchaseOrderId], undefined>,
  'deleteSalesOrder' : ActorMethod<[SalesOrderId], undefined>,
  'deleteSupplier' : ActorMethod<[SupplierId], undefined>,
  'getAccountsReceivable' : ActorMethod<[], Array<CustomerReceivable>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllPurchaseOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getAllSalesOrders' : ActorMethod<[], Array<SalesOrder>>,
  'getAllSuppliers' : ActorMethod<[], Array<Supplier>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [Customer]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getInventoryValuation' : ActorMethod<[], bigint>,
  'getInvoice' : ActorMethod<[InvoiceId], [] | [Invoice]>,
  'getPayment' : ActorMethod<[PaymentId], [] | [Payment]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getPurchaseOrder' : ActorMethod<[PurchaseOrderId], [] | [PurchaseOrder]>,
  'getSalesOrder' : ActorMethod<[SalesOrderId], [] | [SalesOrder]>,
  'getSalesSummary' : ActorMethod<[Time, Time], SalesSummary>,
  'getSupplier' : ActorMethod<[SupplierId], [] | [Supplier]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomer' : ActorMethod<
    [CustomerId, string, string, string, Address, string],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, string, string, bigint, bigint, bigint],
    undefined
  >,
  'updatePurchaseOrderStatus' : ActorMethod<
    [PurchaseOrderId, PurchaseOrderStatus],
    undefined
  >,
  'updateSalesOrderStatus' : ActorMethod<
    [SalesOrderId, SalesOrderStatus],
    undefined
  >,
  'updateSupplier' : ActorMethod<
    [SupplierId, string, string, string, Address, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];