/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type CustomerId = bigint;
export interface Address {
    zip: string;
    street: string;
    country: string;
    city: string;
    state: string;
}
export type Time = bigint;
export type PaymentMethod = {
    __kind__: "creditCard";
    creditCard: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "cash";
    cash: null;
} | {
    __kind__: "check";
    check: null;
} | {
    __kind__: "bankTransfer";
    bankTransfer: null;
};
export type PurchaseOrderId = bigint;
export interface SalesOrderLineItem {
    productId: ProductId;
    quantity: bigint;
    unitPrice: bigint;
}
export interface SalesSummary {
    totalSales: bigint;
    orderCount: bigint;
}
export interface SalesOrder {
    id: SalesOrderId;
    status: SalesOrderStatus;
    lineItems: Array<SalesOrderLineItem>;
    createdAt: Time;
    confirmedAt?: Time;
    shippedAt?: Time;
    customerId: CustomerId;
}
export interface Payment {
    id: PaymentId;
    method: PaymentMethod;
    invoiceId: InvoiceId;
    notes: string;
    paymentDate: Time;
    amount: bigint;
}
export interface Invoice {
    id: InvoiceId;
    status: InvoiceStatus;
    createdAt: Time;
    dueDate: Time;
    amountPaid: bigint;
    totalAmount: bigint;
    salesOrderId: SalesOrderId;
    customerId: CustomerId;
}
export type SalesOrderId = bigint;
export interface DashboardStats {
    lowStockProducts: Array<Product>;
    outstandingReceivables: bigint;
    totalRevenue: bigint;
    recentSalesOrdersCount: bigint;
}
export interface Customer {
    id: CustomerId;
    name: string;
    email: string;
    address: Address;
    notes: string;
    phone: string;
}
export type PaymentId = bigint;
export type InvoiceId = bigint;
export type SupplierId = bigint;
export interface PurchaseOrderLineItem {
    productId: ProductId;
    quantity: bigint;
    unitCost: bigint;
}
export type ProductId = bigint;
export interface PurchaseOrder {
    id: PurchaseOrderId;
    status: PurchaseOrderStatus;
    lineItems: Array<PurchaseOrderLineItem>;
    createdAt: Time;
    receivedAt?: Time;
    supplierId: SupplierId;
}
export interface Supplier {
    id: SupplierId;
    name: string;
    email: string;
    address: Address;
    notes: string;
    phone: string;
}
export interface CustomerReceivable {
    customerName: string;
    totalOutstanding: bigint;
    customerId: CustomerId;
}
export interface UserProfile {
    name: string;
}
export interface Product {
    id: ProductId;
    sku: string;
    name: string;
    description: string;
    quantityOnHand: bigint;
    category: string;
    reorderLevel: bigint;
    unitCost: bigint;
}
export enum InvoiceStatus {
    paid = "paid",
    unpaid = "unpaid",
    partial = "partial"
}
export enum PurchaseOrderStatus {
    cancelled = "cancelled",
    sent = "sent",
    draft = "draft",
    received = "received"
}
export enum SalesOrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    completed = "completed",
    confirmed = "confirmed",
    draft = "draft"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPayment(invoiceId: InvoiceId, amount: bigint, method: PaymentMethod, notes: string): Promise<PaymentId>;
    adjustStock(productId: ProductId, quantityChange: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCustomer(name: string, email: string, phone: string, address: Address, notes: string): Promise<CustomerId>;
    createInvoice(salesOrderId: SalesOrderId, dueDate: Time): Promise<InvoiceId>;
    createProduct(sku: string, name: string, category: string, description: string, quantityOnHand: bigint, unitCost: bigint, reorderLevel: bigint): Promise<ProductId>;
    createPurchaseOrder(supplierId: SupplierId, lineItems: Array<PurchaseOrderLineItem>): Promise<PurchaseOrderId>;
    createSalesOrder(customerId: CustomerId, lineItems: Array<SalesOrderLineItem>): Promise<SalesOrderId>;
    createSupplier(name: string, email: string, phone: string, address: Address, notes: string): Promise<SupplierId>;
    deleteCustomer(customerId: CustomerId): Promise<void>;
    deleteInvoice(invoiceId: InvoiceId): Promise<void>;
    deletePayment(paymentId: PaymentId): Promise<void>;
    deleteProduct(productId: ProductId): Promise<void>;
    deletePurchaseOrder(purchaseOrderId: PurchaseOrderId): Promise<void>;
    deleteSalesOrder(salesOrderId: SalesOrderId): Promise<void>;
    deleteSupplier(supplierId: SupplierId): Promise<void>;
    getAccountsReceivable(): Promise<Array<CustomerReceivable>>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllPurchaseOrders(): Promise<Array<PurchaseOrder>>;
    getAllSalesOrders(): Promise<Array<SalesOrder>>;
    getAllSuppliers(): Promise<Array<Supplier>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(customerId: CustomerId): Promise<Customer | null>;
    getDashboardStats(): Promise<DashboardStats>;
    getInventoryValuation(): Promise<bigint>;
    getInvoice(invoiceId: InvoiceId): Promise<Invoice | null>;
    getPayment(paymentId: PaymentId): Promise<Payment | null>;
    getProduct(productId: ProductId): Promise<Product | null>;
    getPurchaseOrder(purchaseOrderId: PurchaseOrderId): Promise<PurchaseOrder | null>;
    getSalesOrder(salesOrderId: SalesOrderId): Promise<SalesOrder | null>;
    getSalesSummary(startDate: Time, endDate: Time): Promise<SalesSummary>;
    getSupplier(supplierId: SupplierId): Promise<Supplier | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCustomer(customerId: CustomerId, name: string, email: string, phone: string, address: Address, notes: string): Promise<void>;
    updateProduct(productId: ProductId, sku: string, name: string, category: string, description: string, quantityOnHand: bigint, unitCost: bigint, reorderLevel: bigint): Promise<void>;
    updatePurchaseOrderStatus(purchaseOrderId: PurchaseOrderId, status: PurchaseOrderStatus): Promise<void>;
    updateSalesOrderStatus(salesOrderId: SalesOrderId, status: SalesOrderStatus): Promise<void>;
    updateSupplier(supplierId: SupplierId, name: string, email: string, phone: string, address: Address, notes: string): Promise<void>;
}
import type { Customer as _Customer, CustomerId as _CustomerId, Invoice as _Invoice, InvoiceId as _InvoiceId, InvoiceStatus as _InvoiceStatus, Payment as _Payment, PaymentId as _PaymentId, PaymentMethod as _PaymentMethod, Product as _Product, PurchaseOrder as _PurchaseOrder, PurchaseOrderId as _PurchaseOrderId, PurchaseOrderLineItem as _PurchaseOrderLineItem, PurchaseOrderStatus as _PurchaseOrderStatus, SalesOrder as _SalesOrder, SalesOrderId as _SalesOrderId, SalesOrderLineItem as _SalesOrderLineItem, SalesOrderStatus as _SalesOrderStatus, Supplier as _Supplier, SupplierId as _SupplierId, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPayment(arg0: InvoiceId, arg1: bigint, arg2: PaymentMethod, arg3: string): Promise<PaymentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(arg0, arg1, to_candid_PaymentMethod_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(arg0, arg1, to_candid_PaymentMethod_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async adjustStock(arg0: ProductId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustStock(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCustomer(arg0: string, arg1: string, arg2: string, arg3: Address, arg4: string): Promise<CustomerId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createInvoice(arg0: SalesOrderId, arg1: Time): Promise<InvoiceId> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1);
            return result;
        }
    }
    async createProduct(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createPurchaseOrder(arg0: SupplierId, arg1: Array<PurchaseOrderLineItem>): Promise<PurchaseOrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchaseOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchaseOrder(arg0, arg1);
            return result;
        }
    }
    async createSalesOrder(arg0: CustomerId, arg1: Array<SalesOrderLineItem>): Promise<SalesOrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSalesOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSalesOrder(arg0, arg1);
            return result;
        }
    }
    async createSupplier(arg0: string, arg1: string, arg2: string, arg3: Address, arg4: string): Promise<SupplierId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSupplier(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSupplier(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteCustomer(arg0: CustomerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: InvoiceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deletePayment(arg0: PaymentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deletePurchaseOrder(arg0: PurchaseOrderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePurchaseOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePurchaseOrder(arg0);
            return result;
        }
    }
    async deleteSalesOrder(arg0: SalesOrderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSalesOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSalesOrder(arg0);
            return result;
        }
    }
    async deleteSupplier(arg0: SupplierId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSupplier(arg0);
            return result;
        }
    }
    async getAccountsReceivable(): Promise<Array<CustomerReceivable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountsReceivable();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountsReceivable();
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllPurchaseOrders(): Promise<Array<PurchaseOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPurchaseOrders();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPurchaseOrders();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSalesOrders(): Promise<Array<SalesOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSalesOrders();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSalesOrders();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSuppliers(): Promise<Array<Supplier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSuppliers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSuppliers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: CustomerId): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getInventoryValuation(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryValuation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryValuation();
            return result;
        }
    }
    async getInvoice(arg0: InvoiceId): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: PaymentId): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPurchaseOrder(arg0: PurchaseOrderId): Promise<PurchaseOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseOrder(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseOrder(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesOrder(arg0: SalesOrderId): Promise<SalesOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesOrder(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesOrder(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesSummary(arg0: Time, arg1: Time): Promise<SalesSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesSummary(arg0, arg1);
            return result;
        }
    }
    async getSupplier(arg0: SupplierId): Promise<Supplier | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplier(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplier(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCustomer(arg0: CustomerId, arg1: string, arg2: string, arg3: string, arg4: Address, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updatePurchaseOrderStatus(arg0: PurchaseOrderId, arg1: PurchaseOrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePurchaseOrderStatus(arg0, to_candid_PurchaseOrderStatus_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePurchaseOrderStatus(arg0, to_candid_PurchaseOrderStatus_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSalesOrderStatus(arg0: SalesOrderId, arg1: SalesOrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalesOrderStatus(arg0, to_candid_SalesOrderStatus_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalesOrderStatus(arg0, to_candid_SalesOrderStatus_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSupplier(arg0: SupplierId, arg1: string, arg2: string, arg3: string, arg4: Address, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupplier(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupplier(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_InvoiceStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseOrderStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseOrderStatus): PurchaseOrderStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseOrder_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseOrder): PurchaseOrder {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_SalesOrderStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesOrderStatus): SalesOrderStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_SalesOrder_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesOrder): SalesOrder {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PurchaseOrder]): PurchaseOrder | null {
    return value.length === 0 ? null : from_candid_PurchaseOrder_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SalesOrder]): SalesOrder | null {
    return value.length === 0 ? null : from_candid_SalesOrder_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Supplier]): Supplier | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    method: _PaymentMethod;
    invoiceId: _InvoiceId;
    notes: string;
    paymentDate: _Time;
    amount: bigint;
}): {
    id: PaymentId;
    method: PaymentMethod;
    invoiceId: InvoiceId;
    notes: string;
    paymentDate: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        method: from_candid_PaymentMethod_n13(_uploadFile, _downloadFile, value.method),
        invoiceId: value.invoiceId,
        notes: value.notes,
        paymentDate: value.paymentDate,
        amount: value.amount
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PurchaseOrderId;
    status: _PurchaseOrderStatus;
    lineItems: Array<_PurchaseOrderLineItem>;
    createdAt: _Time;
    receivedAt: [] | [_Time];
    supplierId: _SupplierId;
}): {
    id: PurchaseOrderId;
    status: PurchaseOrderStatus;
    lineItems: Array<PurchaseOrderLineItem>;
    createdAt: Time;
    receivedAt?: Time;
    supplierId: SupplierId;
} {
    return {
        id: value.id,
        status: from_candid_PurchaseOrderStatus_n18(_uploadFile, _downloadFile, value.status),
        lineItems: value.lineItems,
        createdAt: value.createdAt,
        receivedAt: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.receivedAt)),
        supplierId: value.supplierId
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SalesOrderId;
    status: _SalesOrderStatus;
    lineItems: Array<_SalesOrderLineItem>;
    createdAt: _Time;
    confirmedAt: [] | [_Time];
    shippedAt: [] | [_Time];
    customerId: _CustomerId;
}): {
    id: SalesOrderId;
    status: SalesOrderStatus;
    lineItems: Array<SalesOrderLineItem>;
    createdAt: Time;
    confirmedAt?: Time;
    shippedAt?: Time;
    customerId: CustomerId;
} {
    return {
        id: value.id,
        status: from_candid_SalesOrderStatus_n24(_uploadFile, _downloadFile, value.status),
        lineItems: value.lineItems,
        createdAt: value.createdAt,
        confirmedAt: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.confirmedAt)),
        shippedAt: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.shippedAt)),
        customerId: value.customerId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InvoiceId;
    status: _InvoiceStatus;
    createdAt: _Time;
    dueDate: _Time;
    amountPaid: bigint;
    totalAmount: bigint;
    salesOrderId: _SalesOrderId;
    customerId: _CustomerId;
}): {
    id: InvoiceId;
    status: InvoiceStatus;
    createdAt: Time;
    dueDate: Time;
    amountPaid: bigint;
    totalAmount: bigint;
    salesOrderId: SalesOrderId;
    customerId: CustomerId;
} {
    return {
        id: value.id,
        status: from_candid_InvoiceStatus_n8(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        amountPaid: value.amountPaid,
        totalAmount: value.totalAmount,
        salesOrderId: value.salesOrderId,
        customerId: value.customerId
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creditCard: null;
} | {
    other: string;
} | {
    cash: null;
} | {
    check: null;
} | {
    bankTransfer: null;
}): {
    __kind__: "creditCard";
    creditCard: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "cash";
    cash: null;
} | {
    __kind__: "check";
    check: null;
} | {
    __kind__: "bankTransfer";
    bankTransfer: null;
} {
    return "creditCard" in value ? {
        __kind__: "creditCard",
        creditCard: value.creditCard
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "cash" in value ? {
        __kind__: "cash",
        cash: value.cash
    } : "check" in value ? {
        __kind__: "check",
        check: value.check
    } : "bankTransfer" in value ? {
        __kind__: "bankTransfer",
        bankTransfer: value.bankTransfer
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    sent: null;
} | {
    draft: null;
} | {
    received: null;
}): PurchaseOrderStatus {
    return "cancelled" in value ? PurchaseOrderStatus.cancelled : "sent" in value ? PurchaseOrderStatus.sent : "draft" in value ? PurchaseOrderStatus.draft : "received" in value ? PurchaseOrderStatus.received : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    draft: null;
}): SalesOrderStatus {
    return "shipped" in value ? SalesOrderStatus.shipped : "cancelled" in value ? SalesOrderStatus.cancelled : "completed" in value ? SalesOrderStatus.completed : "confirmed" in value ? SalesOrderStatus.confirmed : "draft" in value ? SalesOrderStatus.draft : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
} | {
    partial: null;
}): InvoiceStatus {
    return "paid" in value ? InvoiceStatus.paid : "unpaid" in value ? InvoiceStatus.unpaid : "partial" in value ? InvoiceStatus.partial : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseOrder>): Array<PurchaseOrder> {
    return value.map((x)=>from_candid_PurchaseOrder_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesOrder>): Array<SalesOrder> {
    return value.map((x)=>from_candid_SalesOrder_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n6(_uploadFile, _downloadFile, x));
}
function to_candid_PaymentMethod_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PurchaseOrderStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PurchaseOrderStatus): _PurchaseOrderStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_SalesOrderStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalesOrderStatus): _SalesOrderStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "creditCard";
    creditCard: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "cash";
    cash: null;
} | {
    __kind__: "check";
    check: null;
} | {
    __kind__: "bankTransfer";
    bankTransfer: null;
}): {
    creditCard: null;
} | {
    other: string;
} | {
    cash: null;
} | {
    check: null;
} | {
    bankTransfer: null;
} {
    return value.__kind__ === "creditCard" ? {
        creditCard: value.creditCard
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "cash" ? {
        cash: value.cash
    } : value.__kind__ === "check" ? {
        check: value.check
    } : value.__kind__ === "bankTransfer" ? {
        bankTransfer: value.bankTransfer
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PurchaseOrderStatus): {
    cancelled: null;
} | {
    sent: null;
} | {
    draft: null;
} | {
    received: null;
} {
    return value == PurchaseOrderStatus.cancelled ? {
        cancelled: null
    } : value == PurchaseOrderStatus.sent ? {
        sent: null
    } : value == PurchaseOrderStatus.draft ? {
        draft: null
    } : value == PurchaseOrderStatus.received ? {
        received: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalesOrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    confirmed: null;
} | {
    draft: null;
} {
    return value == SalesOrderStatus.shipped ? {
        shipped: null
    } : value == SalesOrderStatus.cancelled ? {
        cancelled: null
    } : value == SalesOrderStatus.completed ? {
        completed: null
    } : value == SalesOrderStatus.confirmed ? {
        confirmed: null
    } : value == SalesOrderStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
